const EVENT_POOL = [
  // Performance
  { text: "Tonartshöjning" },
  { text: "Fläktmaskin i håret" },
  { text: "Onödigt mycket pyro" },
  { text: "Eld" },
  { text: "Artist utan skor" },
  { text: "Någon går barfota" },
  { text: "Klädbyte!" },
  { text: "Kostym med cape" },
  { text: "Outfit som ser ut att väga 20 kilo" },
  { text: "Overkligt mycket rök" },
  { text: "Operasång i pop-låt" },
  { text: "Gitarrsolo" },
  { text: "Trumsolo" },
  { text: "Sångare i trappa" },
  { text: "Oväntad rap-sektion i en låt som absolut inte behövde rap" },
  { text: "Viskar i mikrofonen" },
  { text: "Artisten skriker sista tonen" },
  { text: "Overkligt lång ton som ingen fattar hur den hålls" },
  { text: "Någon sjunger falskt men självsäkert" },
  { text: "Kärlekslåt" },
  { text: "Dramatisk powerpose (arm rakt ut, blick upp mot ljuset)" },
  { text: "Artist bär hatt" },
  { text: "Artist gör hjärta-tecknet med händerna" },
  { text: "Artist har handskar" },
  { text: "Solglasögon inomhus" },
  { text: "Bar överkropp" },
  { text: "Någon ligger ner och sjunger" },
  { text: "Matchande outfits" },
  { text: "Dansare halkar" },
  { text: "Schlager-diva" },
  { text: "Artist som \"gör comeback\" men ingen minns från vad" },
  { text: "Outfitbyte" },
  { text: "Glitterkavaj" },
  { text: "Artist flyger på scen" },
  { text: "Artist ekar mot kameran" },
  { text: "Dansare lyfter artisten" },
  { text: "Artist stirrar i taket efter uppträdande" },
  { text: "Rosa Kavaj" },
  { text: "Gittarrist stampar i golvet" },
  { text: "Artistens mikrofon är avstängd de första sekunderna" },
  { text: "Någon spelar fiol på scenen" },
  { text: "Artisten faller/snubblar" },
  { text: "Stol som rekvisita" },
  { text: "Genomskinligt tyg" },
  { text: "Artisten har fjädrar på sig" },
  { text: "Dansare i mask" },
  { text: "Någon gör en split på scen" },
  { text: "Artisten river av sig något klädesplagg" },
  { text: "Korslagda armar-pose" },
  { text: "Country-Låt" },
  { text: "Rock-låt" },
  { text: "Absolute Banger Låt!" },

  // Stage / Production
  { text: "Konfettikanon!" },
  { text: "Tekniskstrul" },
  { text: "Artist i sele" },
  { text: "Lasershow" },
  { text: "Flygel på scen" },
  { text: "Snurrande scen" },
  { text: "Glitterregn" },
  { text: "Glitter" },
  { text: "Onödigt stor rekvisita" },
  { text: "Helt mörk scen i 3 sek" },
  { text: "Scenen byter färg 10+ ggr" },
  { text: "Glittriga Skor" },
  { text: "Onödigt mycket glitter" },

  // Hosts
  { text: "Dåligt skämt av programledare" },
  { text: "Presentatör som skämtar och ingen skrattar" },
  { text: "Pinsam green room-intervju" },
  { text: "Programledare byter outfit" },
  { text: "ABBA nämns" },
  { text: "Eurovision nämns" },
  { text: "Thank you Eurovision!!!", exclude: ["melodifestivalen"] },
  { text: "Programledaren dansar" },
  { text: "Programledaren sjunger" },
  { text: "\"Vilken energi!\"" },
  { text: "Snabbrepris", exclude: ["eurovision"] },
  { text: "Hälsning till Eurovision", exclude: ["eurovision"] },
  { text: "\"Vi har ett resultat\"", exclude: ["eurovision"] },
  { text: "Programledaren nämner sin egen karriär" },
  { text: "Kommentator som inte kan uttala artistnamnet", exclude: ["melodifestivalen"] },
  { text: "Green room är awkward tyst i 3 sek" },
  { text: "Programledaren skrattar ensam åt sitt skämt" },
  { text: "Programledaren säger \"Vilken kväll!\"" },
  { text: "Programledaren börjar sjunga" },
  { text: "Referens till tidigare Mello-år", exclude: ["eurovision"] },
  { text: "Gayskämt" },
  { text: "Någon frågar 'Hur känns det'" },
  { text: "Någon dansar i green-room" },
  { text: "Pinsam intervju i mellansnack" },
  { text: "Sociala Medier nämns" },
  { text: "Någon frågar 'Hur mår du'" },
  { text: "Skämt med sexuell anspelning" },
  { text: "Programledare säger 'Tryck på hjärtat'" },
  { text: "'Jag älskar er'" },
  { text: "Programledare säger 'Stort lycka till'" },
  { text: "Programledare säger 'spännande'" },

  // Audience
  { text: "Guldiga glitterhatter" },
  { text: "Publiken gör vågen" },
  { text: "Publikhav med mobillampor" },
  { text: "Fansen sjunger med" },
  { text: "Barn i publiken visas" },
  { text: "Kändis i publiken" },
  { text: "Publikmedlem gråter" },
  { text: "Någon gråter eller blir tårögd" },
  { text: "Flaggor i publiken", exclude: ["melodifestivalen"] },
  { text: "Publikskylt: \"We love [artist]!\"" },
  { text: "Artistens mamma gråter i publiken" },
  { text: "Rosa-fjäderhalsduk i publiken" },
  { text: "Rosa Hatt" },
  { text: "Fans med matchande kläder" },

  // Voting / Results
  { text: "Dramatisk 12-poängspaus" },
  { text: "\"Vi går till omröstning!\"" },
  { text: "Tårar vid resultat" },
  { text: "Resultaträkning tar evigheter" },
  { text: "Skämt om hur lång röstningen är" },
  { text: "Grannländer ger varandra 12 poäng", exclude: ["melodifestivalen"] },
  { text: "Poängutdelare säger \"Good evening Europe!\"", exclude: ["melodifestivalen"] },

  // Mello-specific
  { text: "Thomas G:son skrev den", exclude: ["eurovision"] },
  { text: "Veteran-artist gör comeback" },
  { text: "Sverige röstar på grannland", exclude: ["eurovision"] },
  { text: "Artisten tackar mamma" },
  { text: "Tårfylld intervju backstage" },
  { text: "Debutant med scenskräck" },
  { text: "\"Det här är min dröm\"" },
  { text: "Duett med ögonkontakt" },
  { text: "Artisten pekar mot publiken" },

  // Clichés & Vibes
  { text: "\"Tack Sverige!\" ", exclude: ["eurovision"] },
  { text: "Artisten vinkar med båda händerna" },
  { text: "Violin på scen" },
  { text: "Kommentator säger \"stark insats\"" },
  { text: "Något politiskt" },
  { text: "Extremt långt namn på låt eller artist" },
  { text: "Ett språk du inte kan placera", exclude: ["melodifestivalen"] },
  { text: "Någon säger \"Nu kör vi!\"" },
  { text: "Någon tackar \"hela svenska folket\"", exclude: ["eurovision"] },
  { text: "Någon ropar \"Är ni med oss?!\"" },
  { text: "Texten nämner \"heart\" minst tre gånger"},
  { text: "Låten heter samma sak som refrängen" },
  { text: "Artistens scennamn är ett enda ord" },
];
