const EVENT_POOL = [
  // Performance
  { text: "Tonartshöjning" },
  { text: "Fläktmaskin i håret" },
  { text: "Onödigt mycket pyro" },
  { text: "Eld" },
  { text: "Artist utan skor" },
  { text: "Någon går barfota" },
  { text: "Klädbyte!" },
  { text: "Kostym med cape" },
  { text: "Outfit som ser ut att väga 20 kilo" },
  { text: "Overkligt mycket rök" },
  { text: "Operasång i pop-låt" },
  { text: "Gitarrsolo" },
  { text: "Trumsolo}
  { text: "Falsett-moment" },
  { text: "Sångare i trappa" },
  { text: "Dramatisk paus i sången" },
  { text: "Rap-vers i schlager" },
  { text: "Oväntad rap-sektion i en låt som absolut inte behövde rap" },
  { text: "Viskar i mikrofonen" },
  { text: "Artisten skriker sista tonen" },
  { text: "Overkligt lång ton som ingen fattar hur den hålls" },
  { text: "Dansbreak utan sång" },
  { text: "Någon sjunger falskt men självsäkert" },
  { text: "Kärlekslåt" },
  { text: "Dramatisk powerballad-pose (arm rakt ut, blick upp mot ljuset)" },
  { text: "Artist bär hatt" },
  { text: "Artist gör hjärta-tecknet med händerna" },
  { text: "Artist har handskar" },
  { text: "Solglasögon inomhus" },
  { text: "Bar överkropp" },
  { text: "Någon ligger ner och sjunger" },
  { text: "Matchande outfits" },
  { text: "Dansare halkar" },
  { text: "Schlager-diva", exclude: ["eurovision"] },
  { text: "Artist som \"gör comeback\" men ingen minns från vad" },
  { text: "Outfitbyte" },
  { text: "Glitterkavaj" },
  { text: "Artist flyger på scen" },
  { text: "Gayskämt" },
  { text: "Någon frågar 'Hur känns det'" },
  { text: "Artist ekar mot kameran" },
  { text: "Artist lyfts av dansare" },
  { text: "Någon dansar i green-room" },
  { text: "Pinsam intervju i mellansnack" },
  { text: "Dramatisk Paus" },
  { text: "Programledare Sjunger" },
  { text: "Sociala Medier nämns" },
  { text: "Någon frågar 'Hur mår du'" },
  { text: "Skämt med sexuell anspelning" },
  { text: "Absolute Banger Låt!" },
  { text: "Country-Låt" },
  { text: "Rock-låt" },
  { text: "Programmledare säger 'Tryck på hjärtat' },
  { text: "" },
  { text: "Artist stirrar i taket efter uppträdande" },
  { text: "Rosa Kavaj" },
  { text: "Glitterkavaj" },
  { text: "'Tack Sverige'" },
  { text: "'Jag älskar er'" },
  { text: "Gittarrist stampar i golvet" },
  { text: "'Vi har ett resultat'" },
  { text: "Stelts snack i greenroom" },
  { text: "Programledare säger 'Stort lycka till'" },
  { text: "Glittriga Skor" },
  { text: "Rosa-fjäderhalsduk i publiken" },
  { text: "Rosa Hatt" },
  { text: "Onödigt mycket glitter" },
  { text: "Programledare säger 'spännande'" },
  { text: "" },




  
  // Stage / Production
  { text: "LED-skärmar gör för mycket" },
  { text: "Konfettikanon!" },
  { text: "Tekniskt strul" },
  { text: "Teknisk miss (mikrofon, ljus eller kamera failar)" },
  { text: "Kameran på fel person" },
  { text: "Förvirrande kameraåkning" },
  { text: "Artist i sele/harness" },
  { text: "Drönarbild" },
  { text: "Lasershow" },
  { text: "Rökmaskin + spotlight" },
  { text: "Catwalk-moment" },
  { text: "Genomskinlig flygel" },
  { text: "Snurrande scen" },
  { text: "Glitterregn" },
  { text: "Glitter" },
  { text: "Vattenfontän/regn på scen" },
  { text: "Onödigt stor rekvisita" },
  { text: "Helt mörk scen i 3 sek" },
  { text: "Scenen byter färg 10+ ggr" },

  // Hosts
  { text: "Dåligt skämt av programledare" },
  { text: "Presentatör som skämtar och ingen skrattar" },
  { text: "Pinsam green room-intervju" },
  { text: "Programledarbyte av outfit" },
  { text: "ABBA nämns" },
  { text: "Eurovision nämns" },
  { text: "Thank you Intervision!!!", exclude: ["melodifestivalen"] },
  { text: "Programledaren dansar" },
  { text: "Programledaren sjunger" },
  { text: "\"Vilken energi!\"" },
  { text: "Melodifestivalen-recap montage", exclude: ["eurovision"] },
  { text: "Hälsning till Eurovision", exclude: ["eurovision"] },
  { text: "Programledaren skämtar om åldern" },
  { text: "\"Sverige, det är dags att rösta!\"", exclude: ["eurovision"] },
  { text: "Programledaren nämner sin egen karriär" },
  { text: "Konstigt skratt i green room-intervju" },
  { text: "\"Det här kan gå hela vägen till Eurovision!\"", exclude: ["eurovision"] },
  { text: "Kommentator som inte kan uttala artistnamnet", exclude: ["melodifestivalen"] },
  { text: "Green room är awkward tyst i 3 sek" },
  { text: "Programledaren skrattar ensam åt sitt skämt" },
  { text: "Programledaren säger \"Vilken kväll!\"" },
  { text: "Programledaren börjar sjunga" },
  { text: "Referens till tidigare Mello-år", exclude: ["eurovision"] },

  // Audience
  { text: "Stående ovation för ballad" },
  { text: "Guldiga glitterhatter" },
  { text: "Publikens armvåg" },
  { text: "Publikvåg!" },
  { text: "Crowd selfie-moment" },
  { text: "Publikhav med mobillampor" },
  { text: "Fansen sjunger med" },
  { text: "Barn i publiken visas" },
  { text: "Kändis i publiken" },
  { text: "Publikmedlem gråter" },
  { text: "Någon gråter eller blir tårögd" },
  { text: "Cosplay/utklädnad i publiken" },
  { text: "Flaggor i publiken", exclude: ["melodifestivalen"] },
  { text: "Publiken booar" },
  { text: "Publikskylt: \"We love you [artist]!\"" },
  { text: "\"We love you!\" från scenen" },
  { text: "Artistens mamma gråter i publiken" },

  // Voting / Results
  { text: "Dramatisk 12-poängspaus" },
  { text: "Jury vs tittare oense" },
  { text: "Överraskande vinnare" },
  { text: "Andrachans-drama", exclude: ["eurovision"] },
  { text: "Poängställning jämnt" },
  { text: "\"Vi går till omröstning!\"" },
  { text: "Tårar vid resultat" },
  { text: "Favoritens kross" },
  { text: "Noll poäng från en jury" },
  { text: "Sista bidraget vinner" },
  { text: "Resultaträkning tar evigheter" },
  { text: "Poängräkning som tar 1000 år" },
  { text: "Skeptisk blick från jury" },
  { text: "Skämt om hur lång röstningen är" },

  // Mello-specific
  { text: "Carola-referens", exclude: ["eurovision"] },
  { text: "Schlagerveteran hyllas" },
  { text: "SchlagU var bättre förr/ hat på nytt", exclude: ["eurovision"] },
  { text: "Thomas G:son skrev den", exclude: ["eurovision"] },
  { text: "Veteran-artist tillbaka" },
  { text: "\"Mello-diva\"-energi", exclude: ["eurovision"] },
  { text: "Sverige röstar på grannland", exclude: ["eurovision"] },
  { text: "Schlager-medley", exclude: ["eurovision"] },
  { text: "Internationell gäst-artist" },
  { text: "Artisten tackar mamma" },
  { text: "Tårfylld intervju backstage" },
  { text: "Debutant med scenskräck" },
  { text: "\"Det här är min dröm\"" },
  { text: "Duett med ögonkontakt" },
  { text: "Artisten pekar mot publiken" },
  { text: "Kärlek till Globen/Friends", exclude: ["eurovision"] },
  { text: "Tryck ansvar" },

  // Clichés & Vibes
  { text: "Låttext om \"vi mot världen\"" },
  { text: "Kärlekslåt med dansgolv-beat" },
  { text: "Ballad med stråkar" },
  { text: "Engelska låten som borde varit svenska", exclude: ["melodifestivalen"] },
  { text: "Artisten tackar Gud" },
  { text: "\"Tack Sverige!\" i mikrofonen", exclude: ["eurovision"] },
  { text: "Onödigt lång outro" },
  { text: "Artisten vinkar med båda händerna" },
  { text: "Slow-motion kameraåkning" },
  { text: "Dramatisk violinsolo" },
  { text: "Någon jämförs med Loreen" },
  { text: "Tävlande artist i publiken sjunger med" },
  { text: "Kommentator säger \"stark insats\"" },
  { text: "Låten slutar med ett skrik" },
  { text: "Artist gör hjärta med händerna" },
  { text: "Något politiskt", exclude: ["melodifestivalen"] },
  { text: "Putin", exclude: ["melodifestivalen"] },
  { text: "Extremt långt namn på ett land eller artist", exclude: ["melodifestivalen"] },
  { text: "Ett språk du inte kan placera", exclude: ["melodifestivalen"] },
  { text: "En duo där en sjunger allt och den andre bara står och ler" },
  { text: "Någon säger \"Nu kör vi!\"" },
  { text: "Nu kör vi" },
  { text: "Någon tackar \"hela svenska folket\"", exclude: ["eurovision"] },
  { text: "Någon ropar \"Är ni med oss?!\"" },
  { text: "Texten nämner \"heart\" minst tre gånger", exclude: ["melodifestivalen"] },
];
