const EVENT_POOL = [
  // Performance
  "Tonartsbyte!",
  "Fläktmaskin i håret",
  "Pyroteknik på scen",
  "Artist utan skor",
  "Kostymavslöjande",
  "Backup-dansare",
  "Talat brygga",
  "Dimmaskin overdose",
  "Operasång i pop-låt",
  "Gitarrsolo",
  "Falsett-moment",
  "Sångare i trappa",
  "Koreografi i formation",
  "Key change final chorus",
  "Dramatisk paus i sången",
  "Helt a cappella-moment",
  "Rap-vers i schlager",
  "Viskning i mikrofonen",
  "Artisten skriker sista tonen",
  "Dansbreak utan sång",

  // Stage / Production
  "LED-skärmar gör för mycket",
  "Konfettikanon!",
  "Tekniskt strul",
  "Kameran på fel person",
  "Artist i sele/harness",
  "Drönarbild",
  "Lasershow",
  "Rökmaskin + spotlight",
  "Catwalk-moment",
  "Genomskinlig flygel",
  "Snurrande scen",
  "Glitterregn",
  "Eldar på scenen",
  "Vattenfontän/regn på scen",
  "Onödigt stor rekvisita",
  "Helt mörk scen i 3 sek",
  "Scenen byter färg 10+ ggr",

  // Hosts
  "Dåligt skämt av programledare",
  "Pinsam green room-intervju",
  "Programledarbyte av outfit",
  "ABBA nämns",
  "Programledaren dansar",
  "Programledaren sjunger",
  "\"Vilken energi!\"",
  "Melodifestivalen-recap montage",
  "Hälsning till Eurovision",
  "Programledaren skämtar om åldern",
  "\"Sverige, det är dags att rösta!\"",
  "Programledaren nämner sin egen karriär",

  // Audience
  "Stående ovation för ballad",
  "Guldiga glitterhatter",
  "Publikens armvåg",
  "Crowd selfie-moment",
  "Publikhav med mobillampor",
  "Fansen sjunger med",
  "Barn i publiken visas",
  "Kändis i publiken",
  "Publikmedlem gråter",
  "Cosplay/utklädnad i publiken",
  "Flaggor i publiken",
  "Publiken booar",

  // Voting / Results
  "Dramatisk 12-poängspaus",
  "Jury vs tittare oense",
  "Överraskande vinnare",
  "Andrachans-drama",
  "Poängställning jämnt",
  "\"Vi går till omröstning!\"",
  "Tårar vid resultat",
  "Favoritens kross",
  "Noll poäng från en jury",
  "Sista bidraget vinner",
  "Resultaträkning tar evigheter",

  // Mello-specific
  "Carola-referens",
  "Schlagerveteran hyllas",
  "Thomas G:son skrev den",
  "Veteran-artist tillbaka",
  "\"Mello-diva\"-energi",
  "Sverige röstar på grannland",
  "Schlager-medley",
  "Internationell gäst-artist",
  "Artisten tackar mamma",
  "Tårfylld intervju backstage",
  "Debutant med scenskräck",
  "\"Det här är min dröm\"",
  "Duett med ögonkontakt",
  "Artisten pekar mot publiken",
  "Kärlek till Globen/Friends",

  // Clichés & Vibes
  "Låttext om \"vi mot världen\"",
  "Kärlekslåt med dansgolv-beat",
  "Ballad med stråkar",
  "Engelska låten som borde varit svenska",
  "Artisten tackar Gud",
  "\"Tack Sverige!\" i mikrofonen",
  "Onödigt lång outro",
  "Artisten vinkar med båda händerna",
  "Slow-motion kameraåkning",
  "Dramatisk violinsolo",
  "Någon jämförs med Loreen",
  "Tävlande artist i publiken sjunger med",
  "Kommentator säger \"stark insats\"",
  "Låten slutar med ett skrik",
  "Artist gör hjärta med händerna",
];
